// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIypOHW7IQJEbd8WCl7LpK5-kK4m-7_jE',
    appId: '1:986887447886:web:5c5d4a23d0b230caccea1f',
    messagingSenderId: '986887447886',
    projectId: 'trackify-f0b56',
    authDomain: 'trackify-f0b56.firebaseapp.com',
    storageBucket: 'trackify-f0b56.appspot.com',
    measurementId: 'G-0352EKMG0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqVIZ6eqMZ63w-IKNoPyxQFr1oeiXTq7k',
    appId: '1:986887447886:android:9a421843508f80cbccea1f',
    messagingSenderId: '986887447886',
    projectId: 'trackify-f0b56',
    storageBucket: 'trackify-f0b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1KqrpP2s6uKFdZuvtO1erzKAGgdILyQ',
    appId: '1:986887447886:ios:de018f011db8ddddccea1f',
    messagingSenderId: '986887447886',
    projectId: 'trackify-f0b56',
    storageBucket: 'trackify-f0b56.appspot.com',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1KqrpP2s6uKFdZuvtO1erzKAGgdILyQ',
    appId: '1:986887447886:ios:6098dccddf570ec2ccea1f',
    messagingSenderId: '986887447886',
    projectId: 'trackify-f0b56',
    storageBucket: 'trackify-f0b56.appspot.com',
    iosBundleId: 'com.example.trackify.RunnerTests',
  );
}
